name: 'Build VSharp'

on:
  workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout VSharp
      uses: actions/checkout@v3
      with:
        submodules: false
    - uses: actions/cache@v3
      id: nuget-cache
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj', '**/*.fsproj') }}
        restore-keys: |
          ${{ runner.os }}-nuget-
    - name: Build VSharp
      run:
        dotnet build -c DebugTailRec
    - uses: actions/upload-artifact@v3
      with:
        name: runner
        path: ./VSharp.Runner/bin/DebugTailRec/netcoreapp6.0
    - uses: actions/upload-artifact@v3
      with:
        name: test_runner
        path: ./VSharp.TestRunner/bin/DebugTailRec/netcoreapp6.0
